# Generated by Django 5.2.11 on 2026-02-05 23:19

import base.models
import django.db.models.deletion
import django_rule_engine.fields.rule_field
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def aplicar_novo_modelo(apps, schema_editor):
    # Verificar se a tabela coorte_papel existe antes de executar
    if schema_editor.connection.introspection.table_names():
        cursor = schema_editor.connection.cursor()
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_name = 'coorte_papel'
            )
        """)
        if not cursor.fetchone()[0]:
            return

    # Inserir Cohorts a partir de CoorteCurso
    schema_editor.execute("""
        INSERT INTO cohort_role (name, shortname, active)
        SELECT  
                nome,
                papel,
                active
        FROM    coorte_papel
        ON CONFLICT DO NOTHING
    """)

    # Inserir Cohorts a partir de CoorteCurso
    schema_editor.execute("""
        INSERT INTO cohort_cohort (name, idnumber, active, role_id, rule_diario, rule_coordenacao, description)
        SELECT  
                c.name,
                c.idnumber,
                c.active,
                (SELECT id FROM cohort_role WHERE shortname = p.papel LIMIT 1) as role_id,
                c.rule_diario,
                c.rule_coordenacao,
                c.description
        FROM    coorte_cohort c INNER JOIN coorte_papel p ON (c.papel_id = p.id)
        ON CONFLICT DO NOTHING
    """)

    # Inserir MoodleUser a partir de User vinculados a CoorteEnrolment
    schema_editor.execute("""
        INSERT INTO cohort_moodleuser (fullname, email, login, active)
        SELECT  
                u.first_name || ' ' || u.last_name,
                u.email,
                u.username,
                is_active
        FROM    coorte_enrolment e INNER JOIN auth_user u ON (e.colaborador_id = u.id)
        ON CONFLICT DO NOTHING
    """)
    
    # Inserir Enrolments a partir de CoorteCurso
    schema_editor.execute("""
        INSERT INTO cohort_enrolment (cohort_id, user_id)
        SELECT  (SELECT c.id FROM cohort_cohort c WHERE idnumber=cc.idnumber LIMIT 1) cohort_id,
                (SELECT m.id FROM cohort_moodleuser m WHERE m.login=u.username LIMIT 1) user_id
        FROM    coorte_enrolment ce
                   INNER JOIN coorte_cohort cc ON (ce.cohort_id = cc.id) 
                   INNER JOIN auth_user u ON (ce.colaborador_id = u.id)
        ON CONFLICT DO NOTHING
    """)

def reverter_novo_modelo(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=2560, unique=True, verbose_name="nome da coorte"
                    ),
                ),
                (
                    "idnumber",
                    models.CharField(
                        max_length=2560, unique=True, verbose_name="idnumber"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="visível")),
                (
                    "rule_diario",
                    django_rule_engine.fields.rule_field.RuleField(
                        blank=True,
                        example_data={
                            "alunos": [
                                {
                                    "email": "",
                                    "email_secundario": "aluno1@teste.local",
                                    "id": 1,
                                    "matricula": "20261132456RN0001",
                                    "nome": "Aluno um",
                                    "polo": {"descricao": "Nome do polo (RN)", "id": 3},
                                    "programa": "UAB",
                                    "situacao": "ativo",
                                    "situacao_diario": "ativo",
                                }
                            ],
                            "campus": {
                                "descricao": "CAMPUS CENTRAL",
                                "id": 1,
                                "sigla": "CENTRAL",
                            },
                            "componente": {
                                "descricao": "Matemática",
                                "descricao_historico": "Matemática",
                                "id": 4321,
                                "optativo": False,
                                "periodo": 1,
                                "qtd_avaliacoes": 1,
                                "sigla": "FIC.1234",
                                "tipo": 1,
                            },
                            "curso": {
                                "codigo": "132456",
                                "descricao": "FIC+ em Alguma Coisa Aí",
                                "id": 123,
                                "nome": "Curso de Formação Inicial e Continuada (FIC) ou Qualificação Profissional em Alguma Coisa Aí",
                            },
                            "diario": {
                                "descricao": "Matemática",
                                "descricao_historico": "Matemática",
                                "id": 123456,
                                "sigla": "FIC.1234",
                                "situacao": "Aberto",
                                "tipo": "regular",
                            },
                            "polo": {"descricao": "Nome do polo (RN)", "id": 3},
                            "professores": [
                                {
                                    "email": "professor.onze@email.local",
                                    "email_secundario": "professor.onze@email.local",
                                    "id": 11,
                                    "login": "12345611",
                                    "nome": "Professor onze",
                                    "status": "ativo",
                                    "tipo": "Principal",
                                },
                                {
                                    "email": "professor.doze@email.local",
                                    "email_secundario": "professor.doze@email.local",
                                    "id": 12,
                                    "login": "12345612",
                                    "nome": "Professor doze",
                                    "status": "ativo",
                                    "tipo": "Formador",
                                },
                                {
                                    "email": "professor.treze@email.local",
                                    "email_secundario": "professor.treze@email.local",
                                    "id": 13,
                                    "login": "12345613",
                                    "nome": "Professor treze",
                                    "status": "ativo",
                                    "tipo": "Tutor",
                                },
                                {
                                    "email": "professor.quatorze@email.local",
                                    "email_secundario": "professor.quatorze@email.local",
                                    "id": 14,
                                    "login": "12345614",
                                    "nome": "Professor quatorze",
                                    "status": "inativo",
                                    "tipo": "Mediador",
                                },
                            ],
                            "turma": {"codigo": "20261.1.132456.123.1M", "id": 1234},
                        },
                        help_text="Exemplos: <ul><li>curso.codigo == '132456'</li></ul>",
                        null=True,
                        verbose_name="regra de validação para diário",
                    ),
                ),
                (
                    "rule_coordenacao",
                    django_rule_engine.fields.rule_field.RuleField(
                        blank=True,
                        example_data={
                            "alunos": [
                                {
                                    "email": "",
                                    "email_secundario": "aluno1@teste.local",
                                    "id": 1,
                                    "matricula": "20261132456RN0001",
                                    "nome": "Aluno um",
                                    "polo": {"descricao": "Nome do polo (RN)", "id": 3},
                                    "programa": "UAB",
                                    "situacao": "ativo",
                                    "situacao_diario": "ativo",
                                }
                            ],
                            "campus": {
                                "descricao": "CAMPUS CENTRAL",
                                "id": 1,
                                "sigla": "CENTRAL",
                            },
                            "componente": {
                                "descricao": "Matemática",
                                "descricao_historico": "Matemática",
                                "id": 4321,
                                "optativo": False,
                                "periodo": 1,
                                "qtd_avaliacoes": 1,
                                "sigla": "FIC.1234",
                                "tipo": 1,
                            },
                            "curso": {
                                "codigo": "132456",
                                "descricao": "FIC+ em Alguma Coisa Aí",
                                "id": 123,
                                "nome": "Curso de Formação Inicial e Continuada (FIC) ou Qualificação Profissional em Alguma Coisa Aí",
                            },
                            "diario": {
                                "descricao": "Matemática",
                                "descricao_historico": "Matemática",
                                "id": 123456,
                                "sigla": "FIC.1234",
                                "situacao": "Aberto",
                                "tipo": "regular",
                            },
                            "polo": {"descricao": "Nome do polo (RN)", "id": 3},
                            "professores": [
                                {
                                    "email": "professor.onze@email.local",
                                    "email_secundario": "professor.onze@email.local",
                                    "id": 11,
                                    "login": "12345611",
                                    "nome": "Professor onze",
                                    "status": "ativo",
                                    "tipo": "Principal",
                                },
                                {
                                    "email": "professor.doze@email.local",
                                    "email_secundario": "professor.doze@email.local",
                                    "id": 12,
                                    "login": "12345612",
                                    "nome": "Professor doze",
                                    "status": "ativo",
                                    "tipo": "Formador",
                                },
                                {
                                    "email": "professor.treze@email.local",
                                    "email_secundario": "professor.treze@email.local",
                                    "id": 13,
                                    "login": "12345613",
                                    "nome": "Professor treze",
                                    "status": "ativo",
                                    "tipo": "Tutor",
                                },
                                {
                                    "email": "professor.quatorze@email.local",
                                    "email_secundario": "professor.quatorze@email.local",
                                    "id": 14,
                                    "login": "12345614",
                                    "nome": "Professor quatorze",
                                    "status": "inativo",
                                    "tipo": "Mediador",
                                },
                            ],
                            "turma": {"codigo": "20261.1.132456.123.1M", "id": 1234},
                        },
                        null=True,
                        verbose_name="regra de validação para sala de coordenação",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
            ],
            options={
                "verbose_name": "coorte",
                "verbose_name_plural": "coortes",
                "ordering": ["name"],
            },
            bases=(base.models.ActiveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MoodleUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        max_length=2560, verbose_name="nome completo do usuário"
                    ),
                ),
                (
                    "email",
                    models.CharField(max_length=2560, verbose_name="email do usuário"),
                ),
                (
                    "login",
                    models.CharField(max_length=2560, verbose_name="login do usuário"),
                ),
                (
                    "active",
                    models.BooleanField(
                        help_text="Indica se a sincronização do usuário com o Moodle está ativa. Inativar aqui não remove o usuário do Moodle nem o inativa no Moodle, apenas indica que ele não deve ser sincronizado.",
                        verbose_name="sincronizar com o Moodle",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuário",
                "verbose_name_plural": "usuários",
                "ordering": ["fullname"],
            },
            bases=(base.models.ActiveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Este atributo será cohort.name Ex.: <sup>ZL.CooCurso.15056</sup>, <sup>ZL.CooPolo.Caraubas(RN)</sup>, <sup>ZL.MedPedProg.UAB</sup>.",
                        max_length=256,
                        verbose_name="nome da role",
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        help_text="Este atributo deve ser conforme role.shortname. Ex.: <sup>teachercoordenadorcurso</sup>, <sup>coordenadordepolo</sup>, <sup>coordenadordeprograma</sup>",
                        max_length=256,
                        verbose_name="shortname da role",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        help_text="Indica se esta coorte deverá ser sincronizada",
                        verbose_name="ativo?",
                    ),
                ),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
                "ordering": ["name"],
            },
            bases=(base.models.ActiveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRole",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Este atributo será cohort.name Ex.: <sup>ZL.CooCurso.15056</sup>, <sup>ZL.CooPolo.Caraubas(RN)</sup>, <sup>ZL.MedPedProg.UAB</sup>.",
                        max_length=256,
                        verbose_name="nome da role",
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        help_text="Este atributo deve ser conforme role.shortname. Ex.: <sup>teachercoordenadorcurso</sup>, <sup>coordenadordepolo</sup>, <sup>coordenadordeprograma</sup>",
                        max_length=256,
                        verbose_name="shortname da role",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        help_text="Indica se esta coorte deverá ser sincronizada",
                        verbose_name="ativo?",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical role",
                "verbose_name_plural": "historical roles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Enrolment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrolments",
                        to="cohort.cohort",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrolments",
                        to="cohort.moodleuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo",
                "verbose_name_plural": "vínculos",
                "ordering": ["cohort", "user"],
            },
        ),
        migrations.AddField(
            model_name="cohort",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cohort_roles",
                to="cohort.role",
            ),
        ),
        migrations.RunPython(aplicar_novo_modelo, reverter_novo_modelo),
    ]
