# Generated by Django 5.2.11 on 2026-02-05 15:38
# Generated by Django 5.2.11 on 2026-02-05 15:38

import base.models
import django.db.models.deletion
import django_rule_engine.fields.rule_field
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=2560, unique=True, verbose_name="nome da coorte"
                    ),
                ),
                (
                    "idnumber",
                    models.CharField(
                        max_length=2560, unique=True, verbose_name="idnumber"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="visível")),
                (
                    "rule_diario",
                    django_rule_engine.fields.rule_field.RuleField(
                        blank=True,
                        example_data={
                            "alunos": [
                                {
                                    "email": "",
                                    "email_secundario": "aluno1@teste.local",
                                    "id": 1,
                                    "matricula": "20261132456RN0001",
                                    "nome": "Aluno um",
                                    "polo": {"descricao": "Nome do polo (RN)", "id": 3},
                                    "programa": "UAB",
                                    "situacao": "ativo",
                                    "situacao_diario": "ativo",
                                }
                            ],
                            "campus": {
                                "descricao": "CAMPUS CENTRAL",
                                "id": 1,
                                "sigla": "CENTRAL",
                            },
                            "componente": {
                                "descricao": "Matemática",
                                "descricao_historico": "Matemática",
                                "id": 4321,
                                "optativo": False,
                                "periodo": 1,
                                "qtd_avaliacoes": 1,
                                "sigla": "FIC.1234",
                                "tipo": 1,
                            },
                            "curso": {
                                "codigo": "132456",
                                "descricao": "FIC+ em Alguma Coisa Aí",
                                "id": 123,
                                "nome": "Curso de Formação Inicial e Continuada (FIC) ou Qualificação Profissional em Alguma Coisa Aí",
                            },
                            "diario": {
                                "descricao": "Matemática",
                                "descricao_historico": "Matemática",
                                "id": 123456,
                                "sigla": "FIC.1234",
                                "situacao": "Aberto",
                                "tipo": "regular",
                            },
                            "polo": {"descricao": "Nome do polo (RN)", "id": 3},
                            "professores": [
                                {
                                    "email": "professor.onze@email.local",
                                    "email_secundario": "professor.onze@email.local",
                                    "id": 11,
                                    "login": "12345611",
                                    "nome": "Professor onze",
                                    "status": "ativo",
                                    "tipo": "Principal",
                                },
                                {
                                    "email": "professor.doze@email.local",
                                    "email_secundario": "professor.doze@email.local",
                                    "id": 12,
                                    "login": "12345612",
                                    "nome": "Professor doze",
                                    "status": "ativo",
                                    "tipo": "Formador",
                                },
                                {
                                    "email": "professor.treze@email.local",
                                    "email_secundario": "professor.treze@email.local",
                                    "id": 13,
                                    "login": "12345613",
                                    "nome": "Professor treze",
                                    "status": "ativo",
                                    "tipo": "Tutor",
                                },
                                {
                                    "email": "professor.quatorze@email.local",
                                    "email_secundario": "professor.quatorze@email.local",
                                    "id": 14,
                                    "login": "12345614",
                                    "nome": "Professor quatorze",
                                    "status": "inativo",
                                    "tipo": "Mediador",
                                },
                            ],
                            "turma": {"codigo": "20261.1.132456.123.1M", "id": 1234},
                        },
                        help_text="Exemplos: <ul><li>curso.codigo == '132456'</li></ul>",
                        null=True,
                        verbose_name="regra de validação para diário",
                    ),
                ),
                (
                    "rule_coordenacao",
                    django_rule_engine.fields.rule_field.RuleField(
                        blank=True,
                        example_data={
                            "alunos": [
                                {
                                    "email": "",
                                    "email_secundario": "aluno1@teste.local",
                                    "id": 1,
                                    "matricula": "20261132456RN0001",
                                    "nome": "Aluno um",
                                    "polo": {"descricao": "Nome do polo (RN)", "id": 3},
                                    "programa": "UAB",
                                    "situacao": "ativo",
                                    "situacao_diario": "ativo",
                                }
                            ],
                            "campus": {
                                "descricao": "CAMPUS CENTRAL",
                                "id": 1,
                                "sigla": "CENTRAL",
                            },
                            "componente": {
                                "descricao": "Matemática",
                                "descricao_historico": "Matemática",
                                "id": 4321,
                                "optativo": False,
                                "periodo": 1,
                                "qtd_avaliacoes": 1,
                                "sigla": "FIC.1234",
                                "tipo": 1,
                            },
                            "curso": {
                                "codigo": "132456",
                                "descricao": "FIC+ em Alguma Coisa Aí",
                                "id": 123,
                                "nome": "Curso de Formação Inicial e Continuada (FIC) ou Qualificação Profissional em Alguma Coisa Aí",
                            },
                            "diario": {
                                "descricao": "Matemática",
                                "descricao_historico": "Matemática",
                                "id": 123456,
                                "sigla": "FIC.1234",
                                "situacao": "Aberto",
                                "tipo": "regular",
                            },
                            "polo": {"descricao": "Nome do polo (RN)", "id": 3},
                            "professores": [
                                {
                                    "email": "professor.onze@email.local",
                                    "email_secundario": "professor.onze@email.local",
                                    "id": 11,
                                    "login": "12345611",
                                    "nome": "Professor onze",
                                    "status": "ativo",
                                    "tipo": "Principal",
                                },
                                {
                                    "email": "professor.doze@email.local",
                                    "email_secundario": "professor.doze@email.local",
                                    "id": 12,
                                    "login": "12345612",
                                    "nome": "Professor doze",
                                    "status": "ativo",
                                    "tipo": "Formador",
                                },
                                {
                                    "email": "professor.treze@email.local",
                                    "email_secundario": "professor.treze@email.local",
                                    "id": 13,
                                    "login": "12345613",
                                    "nome": "Professor treze",
                                    "status": "ativo",
                                    "tipo": "Tutor",
                                },
                                {
                                    "email": "professor.quatorze@email.local",
                                    "email_secundario": "professor.quatorze@email.local",
                                    "id": 14,
                                    "login": "12345614",
                                    "nome": "Professor quatorze",
                                    "status": "inativo",
                                    "tipo": "Mediador",
                                },
                            ],
                            "turma": {"codigo": "20261.1.132456.123.1M", "id": 1234},
                        },
                        null=True,
                        verbose_name="regra de validação para sala de coordenação",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
            ],
            options={
                "verbose_name": "coorte",
                "verbose_name_plural": "coortes",
                "ordering": ["name"],
            },
            bases=(base.models.ActiveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Este atributo será cohort.name Ex.: <sup>Coordenador de curso</sup>, <sup>Coordenador de pólo</sup>, <sup>Coordenador de UAB</sup>.",
                        max_length=256,
                        verbose_name="nome da role",
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        help_text="Este atributo deve ser conforme role.shortname. Ex.: <sup>teachercoordenadorcurso</sup>, <sup>coordenadordepolo</sup>, <sup>coordenadordeprograma</sup>",
                        max_length=256,
                        verbose_name="shortname da role",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        help_text="Indica se esta coorte deverá ser sincronizada",
                        verbose_name="ativo?",
                    ),
                ),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
                "ordering": ["name"],
            },
            bases=(base.models.ActiveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Enrolment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrolments",
                        to="cohort.cohort",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrolments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo",
                "verbose_name_plural": "vínculos",
                "ordering": ["cohort", "user"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalRole",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Este atributo será cohort.name Ex.: <sup>Coordenador de curso</sup>, <sup>Coordenador de pólo</sup>, <sup>Coordenador de UAB</sup>.",
                        max_length=256,
                        verbose_name="nome da role",
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        help_text="Este atributo deve ser conforme role.shortname. Ex.: <sup>teachercoordenadorcurso</sup>, <sup>coordenadordepolo</sup>, <sup>coordenadordeprograma</sup>",
                        max_length=256,
                        verbose_name="shortname da role",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        help_text="Indica se esta coorte deverá ser sincronizada",
                        verbose_name="ativo?",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical role",
                "verbose_name_plural": "historical roles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="cohort",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cohort_roles",
                to="cohort.role",
            ),
        ),
    ]
