# Generated by Django 5.2.11 on 2026-02-05 15:38

import base.models
import django.db.models.deletion
import django_rule_engine.fields.rule_field
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def aplicar_novo_modelo(apps, schema_editor):
    # Verificar se a tabela coorte_papel existe antes de executar
    if schema_editor.connection.introspection.table_names():
        cursor = schema_editor.connection.cursor()
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_name = 'coorte_papel'
            )
        """)
        if not cursor.fetchone()[0]:
            return

    # Inserir Cohorts a partir de CoorteCurso
    schema_editor.execute("""
        INSERT INTO cohort_role (name, shortname, active)
        SELECT  
                nome,
                papel,
                active
        FROM    coorte_papel
        ON CONFLICT DO NOTHING
    """)

    # Inserir Cohorts a partir de CoorteCurso
    schema_editor.execute("""
        INSERT INTO cohort_cohort (name, idnumber, active, role_id, rule_diario, rule_coordenacao, description)
        SELECT  
                c.name,
                c.idnumber,
                c.active,
                (SELECT id FROM cohort_role WHERE shortname = p.papel LIMIT 1) as role_id,
                c.rule_diario,
                c.rule_coordenacao,
                c.description
        FROM    coorte_cohort c INNER JOIN coorte_papel p ON (c.papel_id = p.id)
        ON CONFLICT DO NOTHING
    """)
    
    # Inserir Enrolments a partir de CoorteCurso
    schema_editor.execute("""
        INSERT INTO cohort_enrolment (cohort_id, user_id)
        SELECT  (SELECT c.id FROM cohort_cohort c WHERE idnumber=cc.idnumber) cohort_id,
                ce.colaborador_id
        FROM    coorte_enrolment ce
                   INNER JOIN coorte_cohort cc ON (ce.cohort_id = cc.id) 
        ON CONFLICT DO NOTHING
    """)


def reverter_novo_modelo(apps, schema_editor):
    schema_editor.execute("DELETE FROM cohort_enrolment")
    schema_editor.execute("DELETE FROM cohort_cohort")
    schema_editor.execute("DELETE FROM cohort_role")


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(aplicar_novo_modelo, reverter_novo_modelo),
    ]
