# Generated by Django 5.2.12 on 2026-03-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cohort", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodleuser",
            name="login",
            field=models.CharField(max_length=2560, unique=True, verbose_name="login do usuário"),
        ),
    ]
