# Generated by Django 6.0.4 on 2026-04-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cohort", "0002_alter_moodleuser_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolment",
            name="active",
            field=models.BooleanField(default=True, verbose_name="ativo?"),
        ),
    ]
