# Generated by Django 5.0.3 on 2024-04-05 17:35

import django.db.models.deletion
import integrador.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrador", "0002_alter_solicitacao_campus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suap_id",
                    models.CharField(max_length=255, unique=True, verbose_name="ID do curso no SUAP"),
                ),
                (
                    "codigo",
                    models.CharField(max_length=255, unique=True, verbose_name="código do curso"),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="nome do curso"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="descrição"),
                ),
            ],
            options={
                "verbose_name": "curso",
                "verbose_name_plural": "cursos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Papel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=256, verbose_name="nome do papel"),
                ),
                (
                    "sigla",
                    models.CharField(blank=True, max_length=10, unique=True, verbose_name="sigla"),
                ),
                (
                    "papel",
                    models.CharField(max_length=256, unique=True, verbose_name="papel"),
                ),
                (
                    "contexto",
                    models.CharField(
                        choices=[("c", "Curso"), ("p", "Pólo")],
                        max_length=1,
                        verbose_name="contexto",
                    ),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
            ],
            options={
                "verbose_name": "papel",
                "verbose_name_plural": "papéis",
                "ordering": ["nome"],
            },
            bases=(integrador.models.ActiveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Polo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suap_id",
                    models.CharField(max_length=255, unique=True, verbose_name="ID do pólo no SUAP"),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, unique=True, verbose_name="nome do pólo"),
                ),
            ],
            options={
                "verbose_name": "pólo",
                "verbose_name_plural": "pólos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCurso",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "suap_id",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="ID do curso no SUAP",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(db_index=True, max_length=255, verbose_name="código do curso"),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="nome do curso"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="descrição"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical curso",
                "verbose_name_plural": "historical cursos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPapel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "nome",
                    models.CharField(max_length=256, verbose_name="nome do papel"),
                ),
                (
                    "sigla",
                    models.CharField(blank=True, db_index=True, max_length=10, verbose_name="sigla"),
                ),
                (
                    "papel",
                    models.CharField(db_index=True, max_length=256, verbose_name="papel"),
                ),
                (
                    "contexto",
                    models.CharField(
                        choices=[("c", "Curso"), ("p", "Pólo")],
                        max_length=1,
                        verbose_name="contexto",
                    ),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical papel",
                "verbose_name_plural": "historical papéis",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPolo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "suap_id",
                    models.CharField(db_index=True, max_length=255, verbose_name="ID do pólo no SUAP"),
                ),
                (
                    "nome",
                    models.CharField(db_index=True, max_length=255, verbose_name="nome do pólo"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pólo",
                "verbose_name_plural": "historical pólos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVinculoCurso",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="integrador.campus",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="integrador.curso",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"contexto": "c"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="integrador.papel",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vínculo no curso",
                "verbose_name_plural": "historical cursos x colaboradores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVinculoPolo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"contexto": "p"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="integrador.papel",
                    ),
                ),
                (
                    "polo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="integrador.polo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vínculo no pólo",
                "verbose_name_plural": "historical pólos X colaboradores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCursoPolo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="integrador.campus",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="integrador.curso",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "polo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="integrador.polo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pólo do curso",
                "verbose_name_plural": "historical pólos x cursos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CursoPolo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrador.campus",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrador.curso",
                    ),
                ),
                (
                    "polo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrador.polo",
                    ),
                ),
            ],
            options={
                "verbose_name": "pólo do curso",
                "verbose_name_plural": "pólos x cursos",
                "ordering": ["curso", "polo"],
            },
            bases=(integrador.models.ActiveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VinculoCurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrador.campus",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos_cursos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrador.curso",
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        limit_choices_to={"contexto": "c"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrador.papel",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo no curso",
                "verbose_name_plural": "cursos x colaboradores",
                "ordering": ["papel", "curso", "colaborador"],
            },
            bases=(integrador.models.ActiveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VinculoPolo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos_polos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        limit_choices_to={"contexto": "p"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrador.papel",
                    ),
                ),
                (
                    "polo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrador.polo",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo no pólo",
                "verbose_name_plural": "pólos X colaboradores",
                "ordering": ["papel", "polo", "colaborador"],
            },
            bases=(integrador.models.ActiveMixin, models.Model),
        ),
    ]
