# Generated by Django 5.0 on 2024-11-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "integrador",
            "0003_curso_papel_polo_historicalcurso_historicalpapel_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ambiente",
            name="cor_mestra",
        ),
    ]
