# Generated by Django 5.1 on 2024-11-02 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrador", "0004_remove_ambiente_cor_mestra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campus",
            name="descricao",
        ),
    ]
