# Generated by Django 5.1 on 2024-12-09 21:30

import django.db.models.deletion
import integrador.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrador", "0005_remove_campus_descricao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Programa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suap_id",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="ID do programa no SUAP",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="nome do programa"
                    ),
                ),
                (
                    "sigla",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="sigla do programa"
                    ),
                ),
            ],
            options={
                "verbose_name": "programa",
                "verbose_name_plural": "programas",
                "ordering": ["nome"],
            },
        ),
        migrations.AlterField(
            model_name="historicalpapel",
            name="contexto",
            field=models.CharField(
                choices=[("c", "Curso"), ("p", "Pólo"), ("P", "Programa")],
                max_length=1,
                verbose_name="contexto",
            ),
        ),
        migrations.AlterField(
            model_name="papel",
            name="contexto",
            field=models.CharField(
                choices=[("c", "Curso"), ("p", "Pólo"), ("P", "Programa")],
                max_length=1,
                verbose_name="contexto",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalPrograma",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "suap_id",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="ID do programa no SUAP",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="nome do programa"
                    ),
                ),
                (
                    "sigla",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="sigla do programa"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical programa",
                "verbose_name_plural": "historical programas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVinculoPrograma",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"contexto": "P"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="integrador.papel",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="integrador.programa",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vínculo no programa",
                "verbose_name_plural": "historical programas X colaboradores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCursoPrograma",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="integrador.campus",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="integrador.curso",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="integrador.programa",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical programa do curso",
                "verbose_name_plural": "historical programas x cursos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CursoPrograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrador.campus",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrador.curso",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrador.programa",
                    ),
                ),
            ],
            options={
                "verbose_name": "programa do curso",
                "verbose_name_plural": "programas x cursos",
                "ordering": ["curso", "programa"],
            },
            bases=(integrador.models.ActiveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VinculoPrograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos_programas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        limit_choices_to={"contexto": "P"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrador.papel",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrador.programa",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo no programa",
                "verbose_name_plural": "programas X colaboradores",
                "ordering": ["papel", "programa", "colaborador"],
            },
            bases=(integrador.models.ActiveMixin, models.Model),
        ),
    ]
