# Generated by Django 5.2.4 on 2025-07-14 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrador", "0006_remove_vinculocurso_curso_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seletor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expressao_regular",
                    models.CharField(max_length=2550, verbose_name="expressão regular"),
                ),
                ("ordem", models.IntegerField(default=0, verbose_name="ordem")),
                ("active", models.BooleanField(verbose_name="ativo?")),
                (
                    "ambiente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrador.ambiente",
                    ),
                ),
            ],
            options={
                "verbose_name": "seletor",
                "verbose_name_plural": "seletores",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
