# Generated by Django 5.1.4 on 2025-03-13 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("integrador", "0006_programa_alter_historicalpapel_contexto_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpapel",
            name="contexto",
            field=models.CharField(
                choices=[
                    ("c", "Curso"),
                    ("p", "Pólo"),
                    ("P", "Programa"),
                    ("C", "Coorte"),
                ],
                max_length=1,
                verbose_name="contexto",
            ),
        ),
        migrations.AlterField(
            model_name="papel",
            name="contexto",
            field=models.CharField(
                choices=[
                    ("c", "Curso"),
                    ("p", "Pólo"),
                    ("P", "Programa"),
                    ("C", "Coorte"),
                ],
                max_length=1,
                verbose_name="contexto",
            ),
        ),
        migrations.CreateModel(
            name="Coorte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coorte_papel",
                        to="integrador.papel",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Vinculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coorte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculo_coorte",
                        to="integrador.coorte",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="CoorteCurso",
            fields=[
                (
                    "coorte_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="integrador.coorte",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coorte_curso",
                        to="integrador.curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coorte x curso",
                "verbose_name_plural": "Coorte x Curso",
                "ordering": ["curso"],
            },
            bases=("integrador.coorte",),
        ),
        migrations.CreateModel(
            name="CoortePolo",
            fields=[
                (
                    "coorte_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="integrador.coorte",
                    ),
                ),
                (
                    "polo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coorte_polo",
                        to="integrador.polo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coorte x Polo",
                "verbose_name_plural": "Coorte x Polo",
                "ordering": ["polo"],
            },
            bases=("integrador.coorte",),
        ),
        migrations.CreateModel(
            name="CoortePrograma",
            fields=[
                (
                    "coorte_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="integrador.coorte",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coorte_programa",
                        to="integrador.programa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coorte x Programa",
                "verbose_name_plural": "Coorte x Programa",
                "ordering": ["programa"],
            },
            bases=("integrador.coorte",),
        ),
    ]
