# Generated by Django 5.2.4 on 2025-07-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrador", "0007_seletor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicitacao",
            name="campus",
        ),
        migrations.RemoveField(
            model_name="seletor",
            name="ambiente",
        ),
        migrations.AlterModelOptions(
            name="ambiente",
            options={
                "ordering": ["ordem", "-id"],
                "verbose_name": "ambiente",
                "verbose_name_plural": "ambientes",
            },
        ),
        migrations.AddField(
            model_name="ambiente",
            name="expressao_seletora",
            field=models.TextField(
                default="campus.sigla==ZL'",
                max_length=2550,
                verbose_name="expressão seletora",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ambiente",
            name="ordem",
            field=models.IntegerField(default=0, verbose_name="ordem"),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="campus_sigla",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="sigla do campus"
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="diario_codigo",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="código do diário"
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="diario_id",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="ID do diário"
            ),
        ),
        migrations.DeleteModel(
            name="Campus",
        ),
        migrations.DeleteModel(
            name="Seletor",
        ),
    ]
