# Generated by Django 5.1.4 on 2025-03-19 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrador", "0008_remove_cursoprograma_campus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="integrador.campus",
            ),
        ),
        migrations.AddField(
            model_name="historicalcurso",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrador.campus",
            ),
        ),
    ]
