# Generated by Django 5.2.4 on 2025-07-14 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "integrador",
            "0008_remove_solicitacao_campus_remove_seletor_ambiente_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ambiente",
            options={
                "ordering": ["ordem", "id"],
                "verbose_name": "ambiente",
                "verbose_name_plural": "ambientes",
            },
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="ambiente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="integrador.ambiente",
                verbose_name="ambiente",
            ),
        ),
    ]
