# Generated by Django 5.2.4 on 2025-07-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrador", "0009_alter_ambiente_options_solicitacao_ambiente"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="operacao",
            field=models.CharField(
                choices=[
                    ("SUDiario", "Sync UP: Diário"),
                    ("SDNotas", "Sync DOWN: Notas"),
                ],
                default="SUDiario",
                max_length=256,
                verbose_name="operação",
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("diario", "Diário"),
                    ("fic-", "FIC-"),
                    ("minicurso", "Minicurso"),
                ],
                default="diario",
                max_length=256,
                verbose_name="tipo",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="quando ocorreu"
            ),
        ),
    ]
