# Generated by Django 5.1.4 on 2025-03-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrador", "0009_curso_campus_historicalcurso_campus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalprograma",
            name="suap_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID do programa no SUAP",
            ),
        ),
        migrations.AlterField(
            model_name="programa",
            name="suap_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID do programa no SUAP",
            ),
        ),
    ]
