# Generated by Django 5.1.4 on 2025-03-27 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrador", "0010_alter_historicalprograma_suap_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coortecurso",
            options={
                "ordering": ["curso"],
                "verbose_name": "Coorte x Curso",
                "verbose_name_plural": "Coorte x Curso",
            },
        ),
        migrations.RemoveField(
            model_name="curso",
            name="campus",
        ),
        migrations.RemoveField(
            model_name="historicalcurso",
            name="campus",
        ),
        migrations.AlterField(
            model_name="coortecurso",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coorte_curso",
                to="integrador.curso",
            ),
        ),
        migrations.AlterField(
            model_name="vinculo",
            name="coorte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vinculos",
                to="integrador.coorte",
            ),
        ),
    ]
