# Generated by Django 5.2.10 on 2026-01-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrador", "0010_solicitacao_operacao_solicitacao_tipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacao",
            name="tipo",
            field=models.CharField(
                blank=True, default=None, max_length=256, null=True, verbose_name="tipo"
            ),
        ),
    ]
