# Generated by Django 5.1.7 on 2025-04-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0011_alter_coortecurso_options_remove_curso_campus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinculo',
            options={},
        ),
        migrations.RemoveField(
            model_name='historicalpapel',
            name='contexto',
        ),
        migrations.RemoveField(
            model_name='papel',
            name='contexto',
        ),
        migrations.RemoveField(
            model_name='vinculo',
            name='polymorphic_ctype',
        ),
        migrations.AlterField(
            model_name='historicalpapel',
            name='active',
            field=models.BooleanField(help_text='Indica se esta coorte deverá ser sincronizada', verbose_name='ativo?'),
        ),
        migrations.AlterField(
            model_name='historicalpapel',
            name='nome',
            field=models.CharField(help_text='Este atributo será cohort.name', max_length=256, verbose_name='nome da coorte'),
        ),
        migrations.AlterField(
            model_name='historicalpapel',
            name='papel',
            field=models.CharField(db_index=True, help_text='Este atributo deve ser conforme role.shortname', max_length=256, verbose_name='nome curso do papel'),
        ),
        migrations.AlterField(
            model_name='historicalpapel',
            name='sigla',
            field=models.CharField(blank=True, db_index=True, help_text='Este atributo será o sufixo da cohort.idnumber, ({campus.sigla}.{curso.instanceia.codigo}.{este_sufixo})', max_length=10, verbose_name='sufixo do corteid coorte'),
        ),
        migrations.AlterField(
            model_name='papel',
            name='active',
            field=models.BooleanField(help_text='Indica se esta coorte deverá ser sincronizada', verbose_name='ativo?'),
        ),
        migrations.AlterField(
            model_name='papel',
            name='nome',
            field=models.CharField(help_text='Este atributo será cohort.name', max_length=256, verbose_name='nome da coorte'),
        ),
        migrations.AlterField(
            model_name='papel',
            name='papel',
            field=models.CharField(help_text='Este atributo deve ser conforme role.shortname', max_length=256, unique=True, verbose_name='nome curso do papel'),
        ),
        migrations.AlterField(
            model_name='papel',
            name='sigla',
            field=models.CharField(blank=True, help_text='Este atributo será o sufixo da cohort.idnumber, ({campus.sigla}.{curso.instanceia.codigo}.{este_sufixo})', max_length=10, unique=True, verbose_name='sufixo do corteid coorte'),
        ),
    ]
