# Generated by Django 6.0.4 on 2026-04-09 23:58

import integrador.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrador", "0012_alter_solicitacao_campus_sigla_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambiente",
            name="url",
            field=integrador.models.PermissiveURLField(max_length=255, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="operacao",
            field=models.CharField(
                choices=integrador.models.Solicitacao.Operacao.choices,
                default=integrador.models.Solicitacao.Operacao["SYNC_UP_DIARIO"],
                max_length=256,
                verbose_name="operação",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="status",
            field=models.CharField(
                choices=integrador.models.Solicitacao.Status.choices,
                max_length=256,
                null=True,
                verbose_name="status",
            ),
        ),
    ]
