# Generated by Django 6.0.4 on 2026-04-16 23:58

import sga.db.fields
import sga.db.obfuscators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrador", "0014_remove_ambiente_active_remove_ambiente_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambiente",
            name="expressao_seletora",
            field=models.TextField(blank=True, max_length=2550, null=True, verbose_name="expressão seletora"),
        ),
        migrations.AlterField(
            model_name="ambiente",
            name="local_suap_token",
            field=sga.db.fields.ObfuscatedCharField(
                blank=True,
                max_length=255,
                null=True,
                obfuscator=sga.db.obfuscators.mask_all,
                verbose_name="token local_suap",
            ),
        ),
        migrations.AlterField(
            model_name="ambiente",
            name="tool_sga_token",
            field=sga.db.fields.ObfuscatedCharField(
                blank=True,
                max_length=255,
                null=True,
                obfuscator=sga.db.obfuscators.mask_all,
                verbose_name="token tool_sga",
            ),
        ),
    ]
