# Generated by Django 6.0.4 on 2026-04-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrador", "0015_alter_ambiente_expressao_seletora_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambiente",
            name="local_suap_token",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="token local_suap"),
        ),
        migrations.AlterField(
            model_name="ambiente",
            name="tool_sga_token",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="token tool_sga"),
        ),
    ]
