default_language_version:
  python: python3

default_stages: [pre-commit]
exclude: ^src/htmlcov/

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
        - id: check-added-large-files
        - id: check-ast
        - id: check-builtin-literals
        - id: check-case-conflict
        - id: check-docstring-first
        - id: check-executables-have-shebangs
        - id: check-merge-conflict
        - id: check-shebang-scripts-are-executable
        - id: check-symlinks
        - id: check-toml
        - id: check-vcs-permalinks
        - id: check-xml
        - id: check-yaml
        - id: debug-statements
        - id: destroyed-symlinks
        - id: detect-private-key
        - id: end-of-file-fixer
        - id: fix-byte-order-marker
        - id: mixed-line-ending
        - id: name-tests-test
          args: [--pytest-test-first]
        - id: requirements-txt-fixer
        - id: trailing-whitespace
          args: [--markdown-linebreak-ext=md]

    - repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
        - id: black

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.8
      hooks:
        - id: ruff
          args: [--fix]
        - id: ruff-format

    - repo: https://github.com/PyCQA/bandit
      rev: 1.8.3
      hooks:
        - id: bandit
          args: [-r, src, -x, "src/base/tests.py,src/cohort/tests.py,src/dashboard/tests.py,src/hacks/tests.py,src/health/tests.py,src/integrador/tests.py,src/security/tests.py,src/settings/tests.py"]
          pass_filenames: false

    - repo: https://github.com/rtts/djhtml
      rev: 3.0.11
      hooks:
        - id: djhtml
          files: \.html$
          exclude: ^(migrations|static|media)/

    - repo: https://github.com/semgrep/pre-commit
      rev: v1.159.0
      hooks:
        - id: semgrep
          args: [--config=auto]  # Ou p/django: r/python,django

    - repo: https://github.com/kelsoncm/pytest-coverage-gate
      rev: v1.0.1
      hooks:
        - id: pytest-coverage-gate
          args:
            - --coverage-xml=src/coverage.xml
            - --baseline=src/.coverage-baseline
