### No VSCode, instale o plugin "REST Client" e veja a mágica ocorer :)
### Pressione Ctrl + Alt + R, ou "Send Request", para executar cada request


### Apenas os atributos os obrigatórios
POST http://localhost:8091/api/enviar_diarios/ HTTP/1.1
Authentication: Token changeme


{
    "campus":     {"id": 1,     "sigla":  "NC",                         "descricao": "CAMPUS NC" },
    "curso":      {"id": 22,    "codigo": "999999",                     "nome":      "AAAA"      },
    "componente": {"id": 333,   "sigla":  "TEC.1234",                   "descricao": "BBBB"      },
    "turma":      {"id": 4444,  "codigo": "20262.6.999999.TEC.1234.1E"                           },
    "diario":     {"id": 55555, "sigla":  "TEC.1234",                   "situacao":  "Aberto"    }
}

### Apenas os atributos os obrigatórios
POST http://localhost:8091/api/enviar_diarios/ HTTP/1.1
Authentication: Token changeme


{
    "campus":     {"id": 1,     "sigla":  "NC",                         "descricao": "CAMPUS NC" },
    "curso":      {"id": 22,    "codigo": "999999",                     "nome":      "AAAA"      },
    "componente": {"id": 333,   "sigla":  "TEC.1234",                   "descricao": "BBBB"      },
    "turma":      {"id": 4444,  "codigo": "20262.6.999999.TEC.1234.1E"                           },
    "diario":     {"id": 55555, "sigla":  "TEC.1234",                   "situacao":  "Aberto"    },

    "alunos": [{"matricula": "20260000000001", "email": "", "email_secundario": "aluno1@gmail.com", "situacao": "ativo", "nome": "aluno um", "situacao_diario": "ativo"}]
}


### Todos os atributos nulos, exceto de usuários
POST http://localhost:8091/api/enviar_diarios/ HTTP/1.1
Authentication: Token changeme


{
    "polo": null,
    "campus": {
        "id": 1,
        "sigla": "NC",
        "descricao": "CAMPUS NC"
    },
    "curso": {
        "id": 22,
        "codigo": "999999",
        "nome": "AAAA",

        "descricao": null,
        "descricao_historico": null,
        "titulo_certificado_masculino": null,
        "titulo_certificado_feminino": null,
        "ch_total": null,
        "ch_aula": null,
        "programa": null,
        "autoinstrucional": null,
        "autoinscricao": null,
        "conteudo": null,
        "modalidade": null,
        "restricoes": null
    },
    "componente": {
        "id": 333,
        "sigla": "TEC.1234",
        "descricao": "BBBB",

        "tipo": null,
        "periodo": null,
        "optativo": null,
        "qtd_avaliacoes": null,
        "descricao_historico": null,
        "is_seminario_estagio_docente": null,
        "ch_presencial": null,
        "ch_pratica": null,
        "ch_extensao": null,
        "ch_pcc": null,
        "ch_visita_tecnica": null,
        "ch_semanal_1s": null,
        "ch_semanal_2s": null
    },
    "turma": {
        "id": 4444,
        "codigo": "20262.6.999999.TEC.1234.1E",
        "data_inicio": null,
        "data_fim": null,
        "gerar_matricula": null,
        "modelo_padrao": null,
        "nota_minima": null,
        "completude_minima": null
    },
    "diario": {
        "id": 55555,
        "sigla": "TEC.1234",
        "tipo": null,
        "situacao": null,
        "descricao": null,
        "descricao_historico": null
    }
}


### Todos os atributos preenchidos, exceto de usuários
POST http://localhost:8091/api/enviar_diarios/ HTTP/1.1
Authentication: Token changeme


{
    "polo": null,
    "campus": {
        "id": 1,
        "sigla": "NC",
        "descricao": "CAMPUS NC"
    },
    "curso": {
        "id": 22,
        "codigo": "999999",
        "nome": "AAAA",
        "descricao": "AAAA",

        "descricao_historico": "AAAAAA",
        "titulo_certificado_masculino": "técnico",
        "titulo_certificado_feminino": "técnica",
        "ch_total": 99,
        "ch_aula": 1,
        "programa": "UAB",
        "autoinstrucional": true,
        "autoinscricao": true,
        "conteudo": [
            {
                "descricao": "Aulas",
                "ch": 99
            },
            {
                "descricao": "Webnar",
                "ch": 1
            }
        ],
        "modalidade": {
            "id": 1,
            "descricao": "Educação a Distância",
            "nivel_ensino": {
                "id": 1,
                "descricao": "Técnico"
            }
        },
        "restricoes": [
            {
                "descricao": "Modalidade do curso da matricula",
                "chave": "modalidade.id",
                "restricao": "1"
            },
            {
                "descricao": "Aluno, conforme modalidade do curso",
                "chave": "modalidade.id",
                "restricao": "13"
            },
            {
                "descricao": "Aluno, conforme nível de ensino do curso",
                "chave": "modalidade.nivel_ensino.id",
                "restricao": "1"
            },
            {
                "descricao": "É aluno",
                "chave": "eh_aluno",
                "restricao": "true"
            },
            {
                "descricao": "É servidor",
                "chave": "eh_servidor",
                "restricao": "true"
            },
            {
                "descricao": "É prestador",
                "chave": "eh_prestador",
                "restricao": "true"
            },
            {
                "descricao": "É usuario externo",
                "chave": "eh_usuarioexterno",
                "restricao": "true"
            },
            {
                "descricao": "É docente",
                "chave": "eh_docente",
                "restricao": "true"
            },
            {
                "descricao": "É técnico administrativo",
                "chave": "eh_tecnico_administrativo",
                "restricao": "true"
            },
            {
                "descricao": "É estrangeiro",
                "chave": "eh_estrangeiro",
                "restricao": "true"
            },
            {
                "descricao": "É matriculado no curso",
                "chave": "outras_matriculas.*.curso.codigo",
                "restricao": "99999"
            },
            {
                "descricao": "É matriculado no curso",
                "chave": "outras_matriculas.*.curso.codigo",
                "restricao": "99999"
            }
        ]
    },
    "componente": {
        "id": 333,
        "sigla": "TEC.1234",
        "descricao": "BBBB",

        "tipo": 1,
        "periodo": 6,
        "optativo": true,
        "qtd_avaliacoes": 4,
        "descricao_historico": "BBBB",
        "is_seminario_estagio_docente": true,
        "ch_presencial": 1,
        "ch_pratica": 2,
        "ch_extensao": 3,
        "ch_pcc": 4,
        "ch_visita_tecnica": 5,
        "ch_semanal_1s": 6,
        "ch_semanal_2s": 7
    },
    "turma": {
        "id": 4444,
        "codigo": "20262.6.999999.TEC.1234.1E",
        "data_inicio": "9999-09-09",
        "data_fim": "9999-09-09",
        "gerar_matricula": true,
        "modelo_padrao": true,
        "nota_minima": 70.0000,
        "completude_minima": 100.00
    },
    "diario": {
        "id": 55555,
        "sigla": "TEC.1234",
        "tipo": "regular",
        "situacao": "Aberto",
        "descricao": "CCCCC",
        "descricao_historico": "CCCCC"
    }
}


### Todos os atributos preenchidos, dos usuários apenas os obrigatórios
POST http://localhost:8091/api/enviar_diarios/ HTTP/1.1
Authentication: Token changeme


{
    "polo": null,
    "campus": {
        "id": 1,
        "sigla": "NC",
        "descricao": "CAMPUS NC"
    },
    "curso": {
        "id": 22,
        "codigo": "999999",
        "nome": "AAAA",
        "descricao": "AAAA",

        "descricao_historico": "AAAAAA",
        "titulo_certificado_masculino": "técnico",
        "titulo_certificado_feminino": "técnica",
        "ch_total": 99,
        "ch_aula": 1,
        "programa": "UAB",
        "autoinstrucional": true,
        "autoinscricao": true,
        "conteudo": [
            {
                "descricao": "Aulas",
                "ch": 99
            },
            {
                "descricao": "Webnar",
                "ch": 1
            }
        ],
        "modalidade": {
            "id": 1,
            "descricao": "Educação a Distância",
            "nivel_ensino": {
                "id": 1,
                "descricao": "Técnico"
            }
        },
        "restricoes": [
            {
                "descricao": "Modalidade do curso da matricula",
                "chave": "modalidade.id",
                "restricao": "1"
            },
            {
                "descricao": "Aluno, conforme modalidade do curso",
                "chave": "modalidade.id",
                "restricao": "13"
            },
            {
                "descricao": "Aluno, conforme nível de ensino do curso",
                "chave": "modalidade.nivel_ensino.id",
                "restricao": "1"
            },
            {
                "descricao": "É aluno",
                "chave": "eh_aluno",
                "restricao": "true"
            },
            {
                "descricao": "É servidor",
                "chave": "eh_servidor",
                "restricao": "true"
            },
            {
                "descricao": "É prestador",
                "chave": "eh_prestador",
                "restricao": "true"
            },
            {
                "descricao": "É usuario externo",
                "chave": "eh_usuarioexterno",
                "restricao": "true"
            },
            {
                "descricao": "É docente",
                "chave": "eh_docente",
                "restricao": "true"
            },
            {
                "descricao": "É técnico administrativo",
                "chave": "eh_tecnico_administrativo",
                "restricao": "true"
            },
            {
                "descricao": "É estrangeiro",
                "chave": "eh_estrangeiro",
                "restricao": "true"
            },
            {
                "descricao": "É matriculado no curso",
                "chave": "outras_matriculas.*.curso.codigo",
                "restricao": "99999"
            },
            {
                "descricao": "É matriculado no curso",
                "chave": "outras_matriculas.*.curso.codigo",
                "restricao": "99999"
            }
        ]
    },
    "componente": {
        "id": 333,
        "sigla": "TEC.1234",
        "descricao": "BBBB",

        "tipo": 1,
        "periodo": 6,
        "optativo": true,
        "qtd_avaliacoes": 4,
        "descricao_historico": "BBBB",
        "is_seminario_estagio_docente": true,
        "ch_presencial": 1,
        "ch_pratica": 2,
        "ch_extensao": 3,
        "ch_pcc": 4,
        "ch_visita_tecnica": 5,
        "ch_semanal_1s": 6,
        "ch_semanal_2s": 7
    },
    "turma": {
        "id": 4444,
        "codigo": "20262.6.999999.TEC.1234.1E",
        "data_inicio": "9999-09-09",
        "data_fim": "9999-09-09",
        "gerar_matricula": true,
        "modelo_padrao": true,
        "nota_minima": 70.0000,
        "completude_minima": 100.00
    },
    "diario": {
        "id": 55555,
        "sigla": "TEC.1234",
        "tipo": "regular",
        "situacao": "Aberto",
        "descricao": "CCCCC",
        "descricao_historico": "CCCCC"
    },
    "alunos": [
        {
            "matricula": "20260000000001",
            "email": "",
            "email_secundario": "aluno1@gmail.com",
            "situacao": "ativo",
            "nome": "aluno um",
            "situacao_diario": "ativo"
        }
    ]
}


### Todos os atributos preenchidos, dos usuários opcionais nulos
POST http://localhost:8091/api/enviar_diarios/ HTTP/1.1
Authentication: Token changeme


{
    "polo": null,
    "campus": {
        "id": 1,
        "sigla": "NC",
        "descricao": "CAMPUS NC"
    },
    "curso": {
        "id": 22,
        "codigo": "999999",
        "nome": "AAAA",
        "descricao": "AAAA",

        "descricao_historico": "AAAAAA",
        "titulo_certificado_masculino": "técnico",
        "titulo_certificado_feminino": "técnica",
        "ch_total": 99,
        "ch_aula": 1,
        "programa": "UAB",
        "autoinstrucional": true,
        "autoinscricao": true,
        "conteudo": [
            {
                "descricao": "Aulas",
                "ch": 99
            },
            {
                "descricao": "Webnar",
                "ch": 1
            }
        ],
        "modalidade": {
            "id": 1,
            "descricao": "Educação a Distância",
            "nivel_ensino": {
                "id": 1,
                "descricao": "Técnico"
            }
        },
        "restricoes": [
            {
                "descricao": "Modalidade do curso da matricula",
                "chave": "modalidade.id",
                "restricao": "1"
            },
            {
                "descricao": "Aluno, conforme modalidade do curso",
                "chave": "modalidade.id",
                "restricao": "13"
            },
            {
                "descricao": "Aluno, conforme nível de ensino do curso",
                "chave": "modalidade.nivel_ensino.id",
                "restricao": "1"
            },
            {
                "descricao": "É aluno",
                "chave": "eh_aluno",
                "restricao": "true"
            },
            {
                "descricao": "É servidor",
                "chave": "eh_servidor",
                "restricao": "true"
            },
            {
                "descricao": "É prestador",
                "chave": "eh_prestador",
                "restricao": "true"
            },
            {
                "descricao": "É usuario externo",
                "chave": "eh_usuarioexterno",
                "restricao": "true"
            },
            {
                "descricao": "É docente",
                "chave": "eh_docente",
                "restricao": "true"
            },
            {
                "descricao": "É técnico administrativo",
                "chave": "eh_tecnico_administrativo",
                "restricao": "true"
            },
            {
                "descricao": "É estrangeiro",
                "chave": "eh_estrangeiro",
                "restricao": "true"
            },
            {
                "descricao": "É matriculado no curso",
                "chave": "outras_matriculas.*.curso.codigo",
                "restricao": "99999"
            },
            {
                "descricao": "É matriculado no curso",
                "chave": "outras_matriculas.*.curso.codigo",
                "restricao": "99999"
            }
        ]
    },
    "componente": {
        "id": 333,
        "sigla": "TEC.1234",
        "descricao": "BBBB",

        "tipo": 1,
        "periodo": 6,
        "optativo": true,
        "qtd_avaliacoes": 4,
        "descricao_historico": "BBBB",
        "is_seminario_estagio_docente": true,
        "ch_presencial": 1,
        "ch_pratica": 2,
        "ch_extensao": 3,
        "ch_pcc": 4,
        "ch_visita_tecnica": 5,
        "ch_semanal_1s": 6,
        "ch_semanal_2s": 7
    },
    "turma": {
        "id": 4444,
        "codigo": "20262.6.999999.TEC.1234.1E",
        "data_inicio": "9999-09-09",
        "data_fim": "9999-09-09",
        "gerar_matricula": true,
        "modelo_padrao": true,
        "nota_minima": 70.0000,
        "completude_minima": 100.00
    },
    "diario": {
        "id": 55555,
        "sigla": "TEC.1234",
        "tipo": "regular",
        "situacao": "Aberto",
        "descricao": "CCCCC",
        "descricao_historico": "CCCCC"
    },
    "alunos": [
        {
            "matricula": "20260000000001",
            "email": "",
            "email_secundario": "aluno1@gmail.com",
            "situacao": "ativo",
            "nome": "aluno um",
            "situacao_diario": "ativo",
            "programa": null,
            "nome_usual": null,
            "nome_social": null,
            "nome_registro": null,
            "cpf": null,
            "passaporte": null,
            "eh_servidor": null,
            "eh_aluno": null,
            "eh_prestador": null,
            "eh_usuarioexterno": null,
            "eh_docente": null,
            "eh_tecnico_administrativo": null,
            "eh_estrangeiro": null,
            "polo": null,
            "outras_matriculas": null
        },
        {
            "matricula": "20260000000002",
            "email": "",
            "email_secundario": "aluno2@gmail.com",
            "situacao": "ativo",
            "nome": "aluno dois",
            "situacao_diario": "ativo",
            "programa": null,
            "nome_usual": null,
            "nome_social": null,
            "nome_registro": null,
            "cpf": null,
            "passaporte": null,
            "eh_servidor": null,
            "eh_aluno": null,
            "eh_prestador": null,
            "eh_usuarioexterno": null,
            "eh_docente": null,
            "eh_tecnico_administrativo": null,
            "eh_estrangeiro": null,
            "polo": {},
            "outras_matriculas": []
        }

    ]
}


### Todos os atributos preenchidos, dos usuários opcionais nulos
POST http://localhost:8091/api/enviar_diarios/ HTTP/1.1
Authentication: Token changeme


{
    "polo": {
        "id": 1,
        "codigo": "20262",
        "descricao": "Polo UAB de Testes"
    },
    "campus": {
        "id": 1,
        "sigla": "NC",
        "descricao": "CAMPUS NC"
    },
    "curso": {
        "id": 22,
        "codigo": "999999",
        "nome": "AAAA",
        "descricao": "AAAA",
        "descricao_historico": "AAAAAA",
        "titulo_certificado_masculino": "técnico",
        "titulo_certificado_feminino": "técnica",
        "ch_total": 99,
        "ch_aula": 1,
        "programa": "UAB",
        "autoinstrucional": true,
        "autoinscricao": true,
        "conteudo": [
            {
                "descricao": "Aulas",
                "ch": 99
            },
            {
                "descricao": "Webnar",
                "ch": 1
            }
        ],
        "modalidade": {
            "id": 1,
            "descricao": "Educação a Distância",
            "nivel_ensino": {
                "id": 1,
                "descricao": "Técnico"
            }
        },
        "restricoes": [
            {
                "descricao": "Modalidade do curso da matricula",
                "chave": "modalidade.id",
                "restricao": "1"
            },
            {
                "descricao": "Aluno, conforme modalidade do curso",
                "chave": "modalidade.id",
                "restricao": "13"
            },
            {
                "descricao": "Aluno, conforme nível de ensino do curso",
                "chave": "modalidade.nivel_ensino.id",
                "restricao": "1"
            },
            {
                "descricao": "É aluno",
                "chave": "eh_aluno",
                "restricao": "true"
            },
            {
                "descricao": "É servidor",
                "chave": "eh_servidor",
                "restricao": "true"
            },
            {
                "descricao": "É prestador",
                "chave": "eh_prestador",
                "restricao": "true"
            },
            {
                "descricao": "É usuario externo",
                "chave": "eh_usuarioexterno",
                "restricao": "true"
            },
            {
                "descricao": "É docente",
                "chave": "eh_docente",
                "restricao": "true"
            },
            {
                "descricao": "É técnico administrativo",
                "chave": "eh_tecnico_administrativo",
                "restricao": "true"
            },
            {
                "descricao": "É estrangeiro",
                "chave": "eh_estrangeiro",
                "restricao": "true"
            },
            {
                "descricao": "É matriculado no curso",
                "chave": "outras_matriculas.*.curso.codigo",
                "restricao": "99999"
            },
            {
                "descricao": "É matriculado no curso",
                "chave": "outras_matriculas.*.curso.codigo",
                "restricao": "99999"
            }
        ]
    },
    "componente": {
        "id": 333,
        "sigla": "TEC.1234",
        "descricao": "BBBB",

        "tipo": 1,
        "periodo": 6,
        "optativo": true,
        "qtd_avaliacoes": 4,
        "descricao_historico": "BBBB",
        "is_seminario_estagio_docente": true,
        "ch_presencial": 1,
        "ch_pratica": 2,
        "ch_extensao": 3,
        "ch_pcc": 4,
        "ch_visita_tecnica": 5,
        "ch_semanal_1s": 6,
        "ch_semanal_2s": 7
    },
    "turma": {
        "id": 4444,
        "codigo": "20262.6.999999.TEC.1234.1E",
        "data_inicio": "9999-09-09",
        "data_fim": "9999-09-09",
        "gerar_matricula": true,
        "modelo_padrao": true,
        "nota_minima": 70.0000,
        "completude_minima": 100.00
    },
    "diario": {
        "id": 55555,
        "sigla": "TEC.1234",
        "tipo": "regular",
        "situacao": "Aberto",
        "descricao": "CCCCC",
        "descricao_historico": "CCCCC"
    },
    "alunos": [
        {
            "matricula": "20260000000001",
            "email": "",
            "email_secundario": "aluno1@gmail.com",
            "situacao": "ativo",
            "nome": "aluno um",
            "situacao_diario": "ativo",
            "programa": "UAB",
            "nome_usual": "ALUNO UM",
            "nome_social": "allumni hum",
            "nome_registro": "Aluno Um",
            "cpf": "12345678901",
            "passaporte": "321654987",
            "eh_servidor": false,
            "eh_aluno": true,
            "eh_prestador": false,
            "eh_usuarioexterno": false,
            "eh_docente": false,
            "eh_tecnico_administrativo": false,
            "eh_estrangeiro": false,
            "polo": {
                "id": 1,
                "sigla": "SGA",
                "descricao": "Polo UAB de Testes"
            },
            "outras_matriculas": [
                {
                    "identificacao": "9999999999AAAA999",
                    "situacao": "ativo",
                    "curso": {
                        "id": 99999,
                        "codigo": "99999",
                        "nome": "O nome do curso pode ser bem grande, pois as pessoas são criativas a dar nome para cursos, mas tem que ser preenchido se a matricula existir"
                    }
                },
                {
                    "identificacao": "88888888888AAAA8888",
                    "situacao": "ativo",
                    "curso": {
                        "id": 888888,
                        "codigo": "88888",
                        "nome": "Como falei, os nomes podem ser bem criativos e grandes, isso ocorrer por insegurança de quem cria a curso, afinal, medicina, direito, engenharia, são nomes de curso tão comuns e sem criatividade, não é mesmo? Por isso, tem gente que gosta de colocar um nome bem grande e criativo para o curso, para mostrar que o curso é diferenciado e especial, mesmo que seja um curso comum e sem graça. Mas o importante é que o nome do curso seja preenchido se a matricula existir, para que possamos identificar qual curso o aluno está matriculado e garantir que ele tenha acesso ao conteúdo e às atividades do curso, afinal, ninguém quer ficar de fora das aulas e das atividades por causa de um nome de curso mal preenchido ou ausente, não é mesmo?"
                    }
                }
            ]
        },
        {
            "matricula": "20260000000002",
            "email": "",
            "email_secundario": "aluno2@gmail.com",
            "situacao": "ativo",
            "nome": "aluno dois",
            "situacao_diario": "ativo",
            "programa": "UAB",
            "nome_usual": "ALUNO DOIS",
            "nome_social": "allumni dois",
            "nome_registro": "Aluno Dois",
            "cpf": null,
            "passaporte": "7Atç98132456789",
            "eh_servidor": false,
            "eh_aluno": true,
            "eh_prestador": false,
            "eh_usuarioexterno": false,
            "eh_docente": false,
            "eh_tecnico_administrativo": false,
            "eh_estrangeiro": true,
            "polo": {},
            "outras_matriculas": []
        }

    ]
}
