# Generated by Django 5.2.4 on 2025-07-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="on_trial",
        ),
        migrations.RemoveField(
            model_name="client",
            name="paid_until",
        ),
    ]
