# Generated by Django 5.2.4 on 2025-07-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_client_on_trial_remove_client_paid_until"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["name"],
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
            },
        ),
        migrations.AlterModelOptions(
            name="domain",
            options={
                "ordering": ["domain"],
                "verbose_name": "domínio",
                "verbose_name_plural": "domínios",
            },
        ),
    ]
