# Generated by Django 5.2.4 on 2025-07-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_client_options_alter_domain_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="tenant",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Domain",
        ),
    ]
