# Generated by Django 5.2.4 on 2025-07-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="tenant",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Domain",
        ),
    ]
