# Generated by Django 5.2 on 2025-04-05 00:24

import base.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('edu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.CharField(choices=[('curso', 'Curso'), ('polo', 'Pólo'), ('programa', 'Programa')], default='curso', help_text='Limita em qual contexto pode ocorrer a ação', max_length=256, verbose_name='aplica-se a')),
                ('nome', models.CharField(help_text='Este atributo será cohort.name Ex.: <sup>Coordenador de curso</sup>, <sup>Coordenador de pólo</sup>, <sup>Coordenador de UAB</sup>.', max_length=256, verbose_name='nome da coorte')),
                ('sigla', models.CharField(blank=True, help_text='Este atributo será o sufixo da cohort.idnumber, ({campus.sigla}.{curso.instanceia.codigo}.{este_sufixo}). Ex.: <sup>COODC</sup>, <sup>COODP</sup>, <sup>COODUAB</sup>', max_length=10, unique=True, verbose_name='sufixo do corteid coorte')),
                ('papel', models.CharField(help_text='Este atributo deve ser conforme role.shortname. Ex.: <sup>teachercoordenadorcurso</sup>, <sup>coordenadordepolo</sup>, <sup>coordenadordeprograma</sup>', max_length=256, verbose_name='nome do papel (role) no curso')),
                ('active', models.BooleanField(help_text='Indica se esta coorte deverá ser sincronizada', verbose_name='ativo?')),
            ],
            options={
                'verbose_name': 'papel',
                'verbose_name_plural': 'papéis',
                'ordering': ['nome'],
            },
            bases=(base.models.ActiveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPapel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('contexto', models.CharField(choices=[('curso', 'Curso'), ('polo', 'Pólo'), ('programa', 'Programa')], default='curso', help_text='Limita em qual contexto pode ocorrer a ação', max_length=256, verbose_name='aplica-se a')),
                ('nome', models.CharField(help_text='Este atributo será cohort.name Ex.: <sup>Coordenador de curso</sup>, <sup>Coordenador de pólo</sup>, <sup>Coordenador de UAB</sup>.', max_length=256, verbose_name='nome da coorte')),
                ('sigla', models.CharField(blank=True, db_index=True, help_text='Este atributo será o sufixo da cohort.idnumber, ({campus.sigla}.{curso.instanceia.codigo}.{este_sufixo}). Ex.: <sup>COODC</sup>, <sup>COODP</sup>, <sup>COODUAB</sup>', max_length=10, verbose_name='sufixo do corteid coorte')),
                ('papel', models.CharField(help_text='Este atributo deve ser conforme role.shortname. Ex.: <sup>teachercoordenadorcurso</sup>, <sup>coordenadordepolo</sup>, <sup>coordenadordeprograma</sup>', max_length=256, verbose_name='nome do papel (role) no curso')),
                ('active', models.BooleanField(help_text='Indica se esta coorte deverá ser sincronizada', verbose_name='ativo?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical papel',
                'verbose_name_plural': 'historical papéis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Coorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coorte_papel', to='coorte.papel')),
            ],
            options={
                'verbose_name': 'Coorte',
                'verbose_name_plural': 'Coortes',
                'ordering': ['papel'],
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('coorte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='coorte.coorte')),
            ],
        ),
        migrations.CreateModel(
            name='CoorteCurso',
            fields=[
                ('coorte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coorte.coorte')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coorte_curso', to='edu.curso')),
            ],
            options={
                'verbose_name': 'Coorte x Curso',
                'verbose_name_plural': 'Coorte x Curso',
                'ordering': ['curso'],
            },
            bases=('coorte.coorte',),
        ),
        migrations.CreateModel(
            name='CoortePolo',
            fields=[
                ('coorte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coorte.coorte')),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coorte_polo', to='edu.polo')),
            ],
            options={
                'verbose_name': 'Coorte x Polo',
                'verbose_name_plural': 'Coorte x Polo',
                'ordering': ['polo'],
            },
            bases=('coorte.coorte',),
        ),
        migrations.CreateModel(
            name='CoortePrograma',
            fields=[
                ('coorte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coorte.coorte')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coorte_programa', to='edu.programa')),
            ],
            options={
                'verbose_name': 'Coorte x Programa',
                'verbose_name_plural': 'Coorte x Programa',
                'ordering': ['programa'],
            },
            bases=('coorte.coorte',),
        ),
    ]
