# Generated by Django 5.2.1 on 2025-05-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coorte", "0002_alter_historicalpapel_sigla_alter_papel_sigla"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpapel",
            name="sigla",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Este atributo será o sufixo da cohort.idnumber, ({campus.sigla}.{este_sufixo}.{curso.instancia.codigo}). Ex.: <sup>COODC</sup>, <sup>COODP</sup>, <sup>COODUAB</sup>",
                max_length=10,
                verbose_name="sufixo do corteid coorte",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="papel",
            name="sigla",
            field=models.CharField(
                default="",
                help_text="Este atributo será o sufixo da cohort.idnumber, ({campus.sigla}.{este_sufixo}.{curso.instancia.codigo}). Ex.: <sup>COODC</sup>, <sup>COODP</sup>, <sup>COODUAB</sup>",
                max_length=10,
                unique=True,
                verbose_name="sufixo do corteid coorte",
            ),
            preserve_default=False,
        ),
    ]
