# Generated by Django 5.2.4 on 2025-07-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coorte", "0003_alter_historicalpapel_sigla_alter_papel_sigla"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="papel",
            options={
                "ordering": ["contexto", "nome"],
                "verbose_name": "papel",
                "verbose_name_plural": "papéis",
            },
        ),
        migrations.AlterModelOptions(
            name="vinculo",
            options={
                "ordering": ["coorte", "colaborador"],
                "verbose_name": "vínculo",
                "verbose_name_plural": "vínculos",
            },
        ),
    ]
