# Generated by Django 5.2.10 on 2026-01-14 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coorte", "0004_alter_papel_options_alter_vinculo_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coortecurso",
            options={
                "ordering": ["curso"],
                "verbose_name": "coortes de curso",
                "verbose_name_plural": "coortes de cursos",
            },
        ),
        migrations.AlterModelOptions(
            name="coortepolo",
            options={
                "ordering": ["polo"],
                "verbose_name": "coorte de polo",
                "verbose_name_plural": "coortes de polos",
            },
        ),
        migrations.AlterModelOptions(
            name="coorteprograma",
            options={
                "ordering": ["programa"],
                "verbose_name": "coortes de programa",
                "verbose_name_plural": "coortes de programas",
            },
        ),
    ]
