# Generated by Django 5.2.10 on 2026-01-19 20:48

import django_rule_engine.fields.rule_field
import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coorte', '0005_alter_coortecurso_options_alter_coortepolo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2560, unique=True, verbose_name='nome da coorte')),
                ('contextid', models.CharField(max_length=2560, verbose_name='id do contexto')),
                ('idnumber', models.CharField(max_length=2560, unique=True, verbose_name='id do contexto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('visible', models.BooleanField(verbose_name='visível')),
                ('rule', django_rule_engine.fields.rule_field.RuleField(blank=True, example_data={'email': 'usuario@example.com', 'login': 'usuario123', 'nome': 'João da Silva', 'status': 'Ativo'}, help_text='Regra para validar vinculação de colaboradores. Use variáveis: login, email, nome, status', null=True, verbose_name='regra de validação')),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohort_papel', to='coorte.papel')),
            ],
            options={
                'verbose_name': 'cohort',
                'verbose_name_plural': 'cohorts',
                'ordering': ['name'],
            },
            bases=(base.models.ActiveMixin, models.Model),
        ),
    ]
