# Generated by Django 5.2.10 on 2026-01-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coorte', '0006_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='idnumber',
            field=models.CharField(max_length=2560, unique=True, verbose_name='idnumber'),
        ),
    ]
