# Generated by Django 5.2.10 on 2026-01-19 23:55

import django_rule_engine.fields.rule_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coorte', '0007_alter_cohort_idnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='rule',
        ),
        migrations.AddField(
            model_name='cohort',
            name='rule_coordenacao',
            field=django_rule_engine.fields.rule_field.RuleField(blank=True, default="login == 'usuario123' and usuario.email != 'usuario123@example.com'", example_data={'alunos': [{'email': '', 'email_secundario': 'aluno1@teste.local', 'id': 1, 'matricula': '20261132456RN0001', 'nome': 'Aluno um', 'polo': {'descricao': 'Nome do polo (RN)', 'id': 3}, 'programa': 'UAB', 'situacao': 'ativo', 'situacao_diario': 'ativo'}], 'campus': {'descricao': 'CAMPUS CENTRAL', 'id': 1, 'sigla': 'CENTRAL'}, 'componente': {'descricao': 'Matemática', 'descricao_historico': 'Matemática', 'id': 4321, 'optativo': False, 'periodo': 1, 'qtd_avaliacoes': 1, 'sigla': 'FIC.1234', 'tipo': 1}, 'curso': {'codigo': '132456', 'descricao': 'FIC+ em Alguma Coisa Aí', 'id': 123, 'nome': 'Curso de Formação Inicial e Continuada (FIC) ou Qualificação Profissional em Alguma Coisa Aí'}, 'diario': {'descricao': 'Matemática', 'descricao_historico': 'Matemática', 'id': 123456, 'sigla': 'FIC.1234', 'situacao': 'Aberto', 'tipo': 'regular'}, 'polo': {'descricao': 'Nome do polo (RN)', 'id': 3}, 'professores': [{'email': 'professor.onze@email.local', 'email_secundario': 'professor.onze@email.local', 'id': 11, 'login': '12345611', 'nome': 'Professor onze', 'status': 'ativo', 'tipo': 'Principal'}, {'email': 'professor.doze@email.local', 'email_secundario': 'professor.doze@email.local', 'id': 12, 'login': '12345612', 'nome': 'Professor doze', 'status': 'ativo', 'tipo': 'Formador'}, {'email': 'professor.treze@email.local', 'email_secundario': 'professor.treze@email.local', 'id': 13, 'login': '12345613', 'nome': 'Professor treze', 'status': 'ativo', 'tipo': 'Tutor'}, {'email': 'professor.quatorze@email.local', 'email_secundario': 'professor.quatorze@email.local', 'id': 14, 'login': '12345614', 'nome': 'Professor quatorze', 'status': 'inativo', 'tipo': 'Mediador'}], 'turma': {'codigo': '20261.1.132456.123.1M', 'id': 1234}}, null=True, verbose_name='regra de validação para diário'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='rule_diario',
            field=django_rule_engine.fields.rule_field.RuleField(blank=True, default="login == 'usuario123' and usuario.email != 'usuario123@example.com'", example_data={'alunos': [{'email': '', 'email_secundario': 'aluno1@teste.local', 'id': 1, 'matricula': '20261132456RN0001', 'nome': 'Aluno um', 'polo': {'descricao': 'Nome do polo (RN)', 'id': 3}, 'programa': 'UAB', 'situacao': 'ativo', 'situacao_diario': 'ativo'}], 'campus': {'descricao': 'CAMPUS CENTRAL', 'id': 1, 'sigla': 'CENTRAL'}, 'componente': {'descricao': 'Matemática', 'descricao_historico': 'Matemática', 'id': 4321, 'optativo': False, 'periodo': 1, 'qtd_avaliacoes': 1, 'sigla': 'FIC.1234', 'tipo': 1}, 'curso': {'codigo': '132456', 'descricao': 'FIC+ em Alguma Coisa Aí', 'id': 123, 'nome': 'Curso de Formação Inicial e Continuada (FIC) ou Qualificação Profissional em Alguma Coisa Aí'}, 'diario': {'descricao': 'Matemática', 'descricao_historico': 'Matemática', 'id': 123456, 'sigla': 'FIC.1234', 'situacao': 'Aberto', 'tipo': 'regular'}, 'polo': {'descricao': 'Nome do polo (RN)', 'id': 3}, 'professores': [{'email': 'professor.onze@email.local', 'email_secundario': 'professor.onze@email.local', 'id': 11, 'login': '12345611', 'nome': 'Professor onze', 'status': 'ativo', 'tipo': 'Principal'}, {'email': 'professor.doze@email.local', 'email_secundario': 'professor.doze@email.local', 'id': 12, 'login': '12345612', 'nome': 'Professor doze', 'status': 'ativo', 'tipo': 'Formador'}, {'email': 'professor.treze@email.local', 'email_secundario': 'professor.treze@email.local', 'id': 13, 'login': '12345613', 'nome': 'Professor treze', 'status': 'ativo', 'tipo': 'Tutor'}, {'email': 'professor.quatorze@email.local', 'email_secundario': 'professor.quatorze@email.local', 'id': 14, 'login': '12345614', 'nome': 'Professor quatorze', 'status': 'inativo', 'tipo': 'Mediador'}], 'turma': {'codigo': '20261.1.132456.123.1M', 'id': 1234}}, help_text="Exemplos: <ul><li>curso.codigo == '132456'</li></ul>", null=True, verbose_name='regra de validação para diário'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='contextid',
            field=models.CharField(default='1', max_length=2560, verbose_name='id do contexto'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visível'),
        ),
    ]
