# Generated by Django 5.2.10 on 2026-01-20 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coorte', '0010_alter_cohort_rule_coordenacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='contextid',
        ),
    ]
