# Generated by Django 5.2.10 on 2026-01-21 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coorte", "0011_remove_cohort_contextid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrolment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="enrolments", to="coorte.cohort"
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "vínculo",
                "verbose_name_plural": "vínculos",
                "ordering": ["cohort", "colaborador"],
            },
        ),
    ]
