# Generated by Django 5.2.10 on 2026-01-20 00:03

from django.db import migrations


def aplicar_novo_modelo(apps, schema_editor):
    # Inserir Cohorts a partir de CoorteCurso
    schema_editor.execute("""
        INSERT INTO coorte_cohort (name, idnumber, visible, papel_id, rule_diario, rule_coordenacao, description)
        SELECT  
                CONCAT('ZL.', p.sigla, '.', cur.codigo) as name,
                CONCAT('ZL.', p.sigla, '.', cur.codigo) as idnumber,
                TRUE as visible,
                c.papel_id,
                CONCAT('curso.codigo == "', cur.codigo, '"') as rule_diario,
                CONCAT('curso.codigo == "', cur.codigo, '"') as rule_coordenacao,
                CONCAT(p.nome, ' do Curso "', cur.nome, '"') as description
        FROM    coorte_coorte c
                    JOIN coorte_papel p ON (c.papel_id = p.id)
                    JOIN coorte_coortecurso cc ON (c.id = cc.coorte_ptr_id)
                    JOIN edu_curso cur ON (cc.curso_id = cur.id)
        ON CONFLICT DO NOTHING
    """)
    
    # Inserir Enrolments a partir de CoorteCurso
    schema_editor.execute("""
        INSERT INTO coorte_enrolment (cohort_id, colaborador_id)
        WITH c AS (
            SELECT  CONCAT('ZL.', p.sigla, '.', cur.codigo) as name, c.id coorte_id
            FROM    coorte_coorte c
                        JOIN coorte_papel p ON (c.papel_id = p.id)
                        JOIN coorte_coortecurso cc ON (c.id = cc.coorte_ptr_id)
                        JOIN edu_curso cur ON (cc.curso_id = cur.id)
        ), c2 AS (
            SELECT  cohort.id cohort_id, c.coorte_id
            FROM    c
                    JOIN coorte_cohort cohort ON (c.name = cohort.name)
        )
        SELECT  c2.cohort_id,
                cv.colaborador_id
        FROM    c2
                    JOIN coorte_vinculo cv ON (c2.coorte_id = cv.coorte_id)
    """)
    
    # Inserir Cohorts a partir de CoortePolo
    schema_editor.execute("""
        INSERT INTO coorte_cohort (name, idnumber, visible, papel_id, rule_diario, rule_coordenacao, description)
        SELECT  
                CONCAT('ZL.', p.sigla, '.', REGEXP_REPLACE(polo.nome, '[^a-zA-Z]', '')) as name,
                CONCAT('ZL.', p.sigla, '.', REGEXP_REPLACE(polo.nome, '[^a-zA-Z]', '')) as idnumber,
                TRUE as visible,
                c.papel_id,
                CONCAT('$any([aluno.polo.descricao == "', polo.nome, '" for aluno in alunos])') as rule_diario,
                CONCAT('$any([aluno.polo.descricao == "', polo.nome, '" for aluno in alunos])') as rule_coordenacao,
                CONCAT(p.nome, ' do Pólo "', polo.nome, '"') as description
        FROM    coorte_coorte c
                    JOIN coorte_papel p ON (c.papel_id = p.id)
                    JOIN coorte_coortepolo cp ON (c.id = cp.coorte_ptr_id)
                    JOIN edu_polo polo ON (cp.polo_id = polo.id)
        ON CONFLICT DO NOTHING                         
    """)
    
    # Inserir Enrolments a partir de CoortePolo
    schema_editor.execute("""
        INSERT INTO coorte_enrolment (cohort_id, colaborador_id)
        WITH c AS (
            SELECT  CONCAT('ZL.', p.sigla, '.', REGEXP_REPLACE(polo.nome, '[^a-zA-Z]', '')) as name, c.id coorte_id
            FROM    coorte_coorte c
                        JOIN coorte_papel p ON (c.papel_id = p.id)
                        JOIN coorte_coortepolo cp ON (c.id = cp.coorte_ptr_id)
                        JOIN edu_polo polo ON (cp.polo_id = polo.id)
        ), n AS (
            SELECT  cohort.id cohort_id, c.coorte_id
            FROM    c
                    JOIN coorte_cohort cohort ON (c.name = cohort.name)
        )
        SELECT  n.cohort_id,
                cv.colaborador_id
        FROM    n
                    JOIN coorte_vinculo cv ON (n.coorte_id = cv.coorte_id)
    """)
    
    # Inserir Cohorts a partir de CoortePrograma
    schema_editor.execute("""
        INSERT INTO coorte_cohort (name, idnumber, visible, papel_id, rule_diario, rule_coordenacao, description)
        SELECT 
                CONCAT('ZL.', p.sigla, '.', prog.sigla) as name,
                CONCAT('ZL.', p.sigla, '.', prog.sigla) as idnumber,
                TRUE as visible,
                c.papel_id,
                CONCAT('$any([aluno.programa == "', prog.sigla, '" for aluno in alunos])') as rule_diario,
                CONCAT('$any([aluno.programa == "', prog.sigla, '" for aluno in alunos])') as rule_coordenacao,
                CONCAT(p.nome, ' do Programa "', prog.nome, '"') as description
        FROM    coorte_coorte c
                    JOIN coorte_papel p ON (c.papel_id = p.id)
                    JOIN coorte_coorteprograma cp ON (c.id = cp.coorte_ptr_id)
                    JOIN edu_programa prog ON (cp.programa_id = prog.id)
        ON CONFLICT DO NOTHING                         
    """)
    
    # Inserir Enrolments a partir de CoortePrograma
    schema_editor.execute("""
        INSERT INTO coorte_enrolment (cohort_id, colaborador_id)
        WITH c AS (
            SELECT  CONCAT('ZL.', p.sigla, '.', prog.sigla) as name, c.id coorte_id
            FROM    coorte_coorte c
                        JOIN coorte_papel p ON (c.papel_id = p.id)
                        JOIN coorte_coorteprograma cp ON (c.id = cp.coorte_ptr_id)
                        JOIN edu_programa prog ON (cp.programa_id = prog.id)
        ), n AS (
            SELECT  cohort.id cohort_id, c.coorte_id
            FROM    c
                    JOIN coorte_cohort cohort ON (c.name = cohort.name)
        )
        SELECT  n.cohort_id,
                cv.colaborador_id
        FROM    n
                    JOIN coorte_vinculo cv ON (n.coorte_id = cv.coorte_id)
    """)


def reverter_novo_modelo(apps, schema_editor):
    # Reverter a migração removendo os registros criados
    Cohort = apps.get_model('coorte', 'Cohort')
    Enrolment = apps.get_model('coorte', 'Enrolment')
    
    # Remover todos os enrolments e cohorts criados
    Enrolment.objects.all().delete()
    Cohort.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('coorte', '0012_enrolment'),
    ]

    operations = [
        migrations.RunPython(aplicar_novo_modelo, reverter_novo_modelo),
    ]
