# Generated by Django 5.2.10 on 2026-01-20 00:03

from django.db import migrations


def aplicar_novo_modelo(apps, schema_editor):
    # Percorre todas as coortes (CoorteCurso, CoortePolo, CoortePrograma) existentes e criar as correspondentes Cohort e Enrolment.
    CoorteCurso = apps.get_model('coorte', 'CoorteCurso')
    CoortePolo = apps.get_model('coorte', 'CoortePolo')
    CoortePrograma = apps.get_model('coorte', 'CoortePrograma')
    Cohort = apps.get_model('coorte', 'Cohort')
    Enrolment = apps.get_model('coorte', 'Enrolment')
    User = apps.get_model('auth', 'User')
    for coorte_model in [CoorteCurso, CoortePolo, CoortePrograma]:
        for coorte in coorte_model.objects.all():
            print(coorte_model)
            # Definir as regras conforme o tipo de coorte
            if coorte_model == CoorteCurso:
                regra_diario = f"curso.codigo == '{coorte.curso.codigo}'"
                rule_coordenacao = regra_diario
                descricao = f'{coorte.papel.sigla} do Curso "{coorte.curso.nome}"'
            elif coorte_model == CoortePolo:
                regra_diario = f"polo:{coorte.polo.id}"
                rule_coordenacao = regra_diario
                descricao = f'{coorte.papel.sigla} do Pólo "{coorte.polo.nome}"'
            elif coorte_model == CoortePrograma:
                regra_diario = f"programa:{coorte.programa.id}"
                rule_coordenacao = regra_diario
                descricao = f'{coorte.papel.sigla} do Programa "{coorte.programa.nome}"'
            else:
                continue  # Não deve ocorrer

            print(regra_diario, rule_coordenacao, coorte.codigo, descricao)

            # Criar a nova Cohort
            cohort = Cohort.objects.create(
                nome=coorte.codigo,
                descricao=descricao,
                data_inicio=coorte.data_inicio,
                data_fim=coorte.data_fim,
                regra_diario=regra_diario,
                regra_coordenacao=rule_coordenacao,
                visivel=coorte.visivel,
            )
            # Migrar os vínculos para enrolments
            vinculos = coorte.vinculo_set.all()
            for vinculo in vinculos:
                Enrolment.objects.create(
                    cohort=cohort,
                    colaborador=vinculo.colaborador,
                    data_matricula=vinculo.data_vinculo,
                )


def reverter_novo_modelo(apps, schema_editor):
    # Reverter a migração removendo os registros criados
    Cohort = apps.get_model('coorte', 'Cohort')
    Enrolment = apps.get_model('coorte', 'Enrolment')
    
    # Remover todos os enrolments e cohorts criados
    Enrolment.objects.all().delete()
    Cohort.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('coorte', '0012_enrolment'),
    ]

    operations = [
        migrations.RunPython(aplicar_novo_modelo, reverter_novo_modelo),
    ]
