# Generated by Django 5.2.10 on 2026-01-20 00:03

from django.db import migrations


def aplicar_novo_modelo(apps, schema_editor):
    # Percorre todas as coortes (CoorteCurso, CoortePolo, CoortePrograma) existentes e criar as correspondentes Cohort e Enrolment.
    import re
    
    CoorteCurso = apps.get_model('coorte', 'CoorteCurso')
    CoortePolo = apps.get_model('coorte', 'CoortePolo')
    CoortePrograma = apps.get_model('coorte', 'CoortePrograma')
    Cohort = apps.get_model('coorte', 'Cohort')
    Enrolment = apps.get_model('coorte', 'Enrolment')
    User = apps.get_model('auth', 'User')
    
    # Processar CoorteCurso
    for coorte in CoorteCurso.objects.all():
        codigo = coorte.curso.codigo  # Campo real do banco
        regra_diario = f"curso.codigo == '{codigo}'"
        rule_coordenacao = regra_diario
        descricao = f'{coorte.papel.sigla} do Curso "{coorte.curso.nome}"'
        idnumber = f"ZL.{coorte.papel.sigla}.{codigo}"
        
        # Criar a nova Cohort
        cohort = Cohort.objects.create(
            name=idnumber,
            idnumber=idnumber,
            visible=True,
            papel=coorte.papel,
            rule_diario=regra_diario,
            rule_coordenacao=rule_coordenacao,
            description=descricao,
        )
        
        # Migrar os vínculos para enrolments
        for vinculo in coorte.vinculos.all():
            Enrolment.objects.create(
                cohort=cohort,
                colaborador=vinculo.colaborador,
            )
    
    # Processar CoortePolo
    for coorte in CoortePolo.objects.all():
        # Polo usa nome com remoção de caracteres não-alfabéticos
        codigo = re.sub(r"[^a-zA-Z]", "", coorte.polo.nome)
        regra_diario = f"polo.id == {coorte.polo.id}"
        rule_coordenacao = regra_diario
        descricao = f'{coorte.papel.sigla} do Pólo "{coorte.polo.nome}"'
        idnumber = f"ZL.{coorte.papel.sigla}.{codigo}"
        
        cohort = Cohort.objects.create(
            name=idnumber,
            idnumber=idnumber,
            visible=True,
            papel=coorte.papel,
            rule_diario=regra_diario,
            rule_coordenacao=rule_coordenacao,
            description=descricao,
        )
        
        for vinculo in coorte.vinculos.all():
            Enrolment.objects.create(
                cohort=cohort,
                colaborador=vinculo.colaborador,
            )
    
    # Processar CoortePrograma
    for coorte in CoortePrograma.objects.all():
        codigo = coorte.programa.sigla  # Campo real do banco
        regra_diario = f"programa == '{coorte.programa.nome}'"
        rule_coordenacao = regra_diario
        descricao = f'{coorte.papel.sigla} do Programa "{coorte.programa.nome}"'
        idnumber = f"ZL.{coorte.papel.sigla}.{codigo}"
        
        cohort = Cohort.objects.create(
            name=idnumber,
            idnumber=idnumber,
            visible=True,
            papel=coorte.papel,
            rule_diario=regra_diario,
            rule_coordenacao=rule_coordenacao,
            description=descricao,
        )
        
        for vinculo in coorte.vinculos.all():
            Enrolment.objects.create(
                cohort=cohort,
                colaborador=vinculo.colaborador,
            )


def reverter_novo_modelo(apps, schema_editor):
    # Reverter a migração removendo os registros criados
    Cohort = apps.get_model('coorte', 'Cohort')
    Enrolment = apps.get_model('coorte', 'Enrolment')
    
    # Remover todos os enrolments e cohorts criados
    Enrolment.objects.all().delete()
    Cohort.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('coorte', '0012_enrolment'),
    ]

    operations = [
        migrations.RunPython(aplicar_novo_modelo, reverter_novo_modelo),
    ]
