# Generated by Django 5.2.10 on 2026-01-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coorte", "0013_novo_modelo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vinculo",
            name="coorte",
        ),
        migrations.RemoveField(
            model_name="coortepolo",
            name="coorte_ptr",
        ),
        migrations.RemoveField(
            model_name="coortecurso",
            name="coorte_ptr",
        ),
        migrations.RemoveField(
            model_name="coorteprograma",
            name="coorte_ptr",
        ),
        migrations.RemoveField(
            model_name="coortecurso",
            name="curso",
        ),
        migrations.RemoveField(
            model_name="coortepolo",
            name="polo",
        ),
        migrations.RemoveField(
            model_name="coorteprograma",
            name="programa",
        ),
        migrations.RemoveField(
            model_name="vinculo",
            name="colaborador",
        ),
        migrations.AlterModelOptions(
            name="cohort",
            options={
                "ordering": ["name"],
                "verbose_name": "coorte",
                "verbose_name_plural": "coortes",
            },
        ),
        migrations.RenameField(
            model_name="cohort",
            old_name="visible",
            new_name="active",
        ),
        migrations.DeleteModel(
            name="Coorte",
        ),
        migrations.DeleteModel(
            name="CoorteCurso",
        ),
        migrations.DeleteModel(
            name="CoortePolo",
        ),
        migrations.DeleteModel(
            name="CoortePrograma",
        ),
        migrations.DeleteModel(
            name="Vinculo",
        ),
    ]
