# Generated by Django 5.2.10 on 2026-01-26 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coorte", "0013_novo_modelo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cohort",
            options={
                "ordering": ["name"],
                "verbose_name": "coorte",
                "verbose_name_plural": "coortes",
            },
        ),
    ]
