# Generated by Django 5.2.10 on 2026-02-01 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coorte", "0014_remove_vinculo_coorte_remove_coortepolo_coorte_ptr_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="papel",
            options={
                "ordering": ["nome"],
                "verbose_name": "papel",
                "verbose_name_plural": "papéis",
            },
        ),
        migrations.RemoveField(
            model_name="historicalpapel",
            name="contexto",
        ),
        migrations.RemoveField(
            model_name="papel",
            name="contexto",
        ),
    ]
