# Generated by Django 5.2.10 on 2026-01-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coorte", "0014_alter_cohort_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cohort",
            old_name="visible",
            new_name="active",
        ),
    ]
