# Generated by Django 5.2 on 2025-04-05 00:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True, verbose_name='ID do curso no SUAP')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='código do curso')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do curso')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True, verbose_name='ID do pólo no SUAP')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='sigla do pólo')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome do pólo')),
            ],
            options={
                'verbose_name': 'pólo',
                'verbose_name_plural': 'pólos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do programa no SUAP')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome do programa')),
                ('sigla', models.CharField(max_length=255, unique=True, verbose_name='sigla do programa')),
            ],
            options={
                'verbose_name': 'programa',
                'verbose_name_plural': 'programas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCurso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('suap_id', models.CharField(db_index=True, max_length=255, verbose_name='ID do curso no SUAP')),
                ('codigo', models.CharField(db_index=True, max_length=255, verbose_name='código do curso')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do curso')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical curso',
                'verbose_name_plural': 'historical cursos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPolo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('suap_id', models.CharField(db_index=True, max_length=255, verbose_name='ID do pólo no SUAP')),
                ('codigo', models.CharField(db_index=True, max_length=255, verbose_name='sigla do pólo')),
                ('nome', models.CharField(db_index=True, max_length=255, verbose_name='nome do pólo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pólo',
                'verbose_name_plural': 'historical pólos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPrograma',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('suap_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do programa no SUAP')),
                ('nome', models.CharField(db_index=True, max_length=255, verbose_name='nome do programa')),
                ('sigla', models.CharField(db_index=True, max_length=255, verbose_name='sigla do programa')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical programa',
                'verbose_name_plural': 'historical programas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
