# Generated by Django 5.2.4 on 2025-12-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpolo",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="polo",
            name="codigo",
        ),
    ]
