# Generated by Django 5.2.4 on 2025-12-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0002_remove_historicalpolo_codigo_remove_polo_codigo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprograma",
            name="suap_id",
        ),
        migrations.RemoveField(
            model_name="programa",
            name="suap_id",
        ),
    ]
