# -*- coding: utf-8 -*-
from sc4py.env import env, env_as_bool, env_as_int
SESSION_ENGINE = env("DJANGO_SESSION_ENGINE", "django.contrib.sessions.backends.cache")
SESSION_CACHE_ALIAS = env("DJANGO_SESSION_CACHE_ALIAS", "default")
SESSION_COOKIE_AGE = env_as_int("DJANGO_SESSION_COOKIE_AGE", 1209600)  # 2 semanas
SESSION_COOKIE_HTTPONLY = env_as_bool("DJANGO_SESSION_COOKIE_HTTPONLY", True)
SESSION_COOKIE_SAMESITE = env("DJANGO_SESSION_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_SECURE = env_as_bool("DJANGO_SESSION_COOKIE_SECURE", False)
SESSION_SAVE_EVERY_REQUEST = env_as_bool("DJANGO_SESSION_SAVE_EVERY_REQUEST", False)
