#!/usr/bin/env python3
"""Coverage quality gate helper for local hooks and CI pipelines."""

from __future__ import annotations

import argparse
import pathlib
import sys
from defusedxml import ElementTree as ET


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate coverage against quality gates.")
    parser.add_argument("--coverage-xml", default="coverage.xml", help="Path to coverage.xml generated by pytest-cov.")
    parser.add_argument(
        "--baseline-file",
        default=".coverage-baseline",
        help="Optional file containing previous coverage percentage (single float line).",
    )
    parser.add_argument("--min", type=float, default=91.0, help="Minimum required total coverage percentage.")
    parser.add_argument("--ideal", type=float, default=95.0, help="Ideal target total coverage percentage.")
    parser.add_argument(
        "--write-baseline",
        action="store_true",
        help="Write current coverage into baseline file after successful validation.",
    )
    parser.add_argument(
        "--tolerance",
        type=float,
        default=0.01,
        help="Tolerance used when comparing current coverage with baseline.",
    )
    return parser.parse_args()


def read_current_coverage(coverage_xml_path: pathlib.Path) -> float:
    if not coverage_xml_path.exists():
        raise FileNotFoundError(f"Coverage report not found: {coverage_xml_path}")

    tree = ET.parse(coverage_xml_path)
    root = tree.getroot()
    line_rate = root.attrib.get("line-rate")
    if line_rate is None:
        raise ValueError("Invalid coverage.xml: missing line-rate attribute in root element.")

    return float(line_rate) * 100.0


def read_baseline(baseline_path: pathlib.Path) -> float | None:
    if not baseline_path.exists():
        return None

    content = baseline_path.read_text(encoding="utf-8").strip()
    if not content:
        return None

    return float(content)


def main() -> int:
    args = parse_args()

    coverage_xml_path = pathlib.Path(args.coverage_xml)
    baseline_path = pathlib.Path(args.baseline_file)

    try:
        current = read_current_coverage(coverage_xml_path)
        baseline = read_baseline(baseline_path)
    except (FileNotFoundError, ValueError) as exc:
        print(f"[coverage-gate] ERROR: {exc}")
        return 1

    print(f"[coverage-gate] Cobertura atual: {current:.2f}%")

    if current + args.tolerance < args.min:
        print(f"[coverage-gate] FAIL: cobertura abaixo do minimo de {args.min:.2f}%")
        return 1

    if baseline is not None and current + args.tolerance < baseline:
        print(f"[coverage-gate] FAIL: cobertura regrediu (atual {current:.2f}% < baseline {baseline:.2f}%)")
        return 1

    if baseline is None:
        print("[coverage-gate] INFO: baseline nao encontrado; comparacao de regressao foi ignorada.")
    else:
        print(f"[coverage-gate] OK: cobertura nao regrediu (baseline {baseline:.2f}%).")

    if current + args.tolerance < args.ideal:
        print(f"[coverage-gate] WARN: cobertura abaixo da meta ideal de {args.ideal:.2f}%.")
    else:
        print(f"[coverage-gate] Excelente: cobertura na meta ideal ({args.ideal:.2f}%+).")

    if args.write_baseline:
        baseline_path.write_text(f"{current:.2f}\n", encoding="utf-8")
        print(f"[coverage-gate] Baseline atualizado em: {baseline_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
