name: Test Deploy via SSH

on:
  push:
    branches:
      - cd/ci
  workflow_dispatch:

jobs:
  deploy:
    # Usando a etiqueta correta que configuramos no GitHub
    runs-on: [self-hosted, runner-dead]

    steps:
      - name: Checar diretorio atual (PWD)
        run: |
          echo "📍 Diretório atual:"
          pwd
          echo "📁 Arquivos nesta pasta:"
          ls -la

      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 10.22.1.212 >> ~/.ssh/known_hosts

      - name: Test SSH and list directory
        run: |
          echo "🔌 Conectando via SSH..."
          ssh root@10.22.1.212 "ls -la /var/dockers_teste"